# This file represents the required schema for the human generated project files.
#
#
#
# Essentially, this file contains nested categorizations of files along with descriptions and names
# at each level.  There are currently three nested categories:
#
# System - Top level category.  This defines the highest level architecure of the project.  For a
# database, this will be things like "queries", "storage", "network", and "utilities".
#
# Module - Nested within System.  This defines more granular functional units in a project.  For
# example, within the "queries" System, you may have the "aggregation", "text search queries", "geo
# queries", and "queries core".
#
# Group - Nested within Module.  This defines logical groupings of files within a functional unit.
# for example, in the "text search queries" module, you may have "stemming" (normalizing words to
# their canonical form), and "stopword handling" (removing things like "and" and "the") as logical
# groups within the "text search queries" module.

### Top level array of all Systems in this project ###
type: array
items:

    ### System Information Object ###
    type: object
    required:
    - system_name
    - system_title
    - system_description
    - system_modules
    additionalProperties: false
    properties:
        # Name of this system with underscores
        system_name:
            type: string
            pattern: "^[_a-z0-9]*$"

        # Name of this system with spaces and capitals
        system_title:
            type: string
            pattern: "^[ a-zA-Z0-9]*$"

        # Description of this system
        system_description:
            type: string

        ### Modules in this system ###
        system_modules:
            type: array
            items:

                ### Module Information Object ###
                type: object
                required:
                - module_name
                - module_title
                - module_description
                - module_groups
                additionalProperties: false
                properties:
                    # Name of this module with underscores
                    module_name:
                        type: string
                        pattern: "^[_a-z0-9]*$"

                    # Name of this module with spaces and capitals
                    module_title:
                        type: string
                        pattern: "^[ a-zA-Z0-9]*$"

                    # Description of this module
                    module_description:
                        type: string

                    ### Logical Groups of files within this Module ###
                    module_groups:
                        type: array
                        items:

                            ### Group Information Object ###
                            type: object
                            required:
                            - group_title
                            - group_description
                            - group_files
                            additionalProperties: false
                            properties:
                                # Name of this group with capitals and spaces
                                group_title:
                                    type: string

                                # Description of this group
                                group_description:
                                    type: string

                                # Files in this group
                                group_files:
                                    type: array
                                    items:

                                        # File name of file in this group
                                        type: string
